server:
  port: 9091
spring:
  application:
    name: Mini-E-Commerce-Order-MS
  datasource:
    url: jdbc:postgresql://localhost:5432/order-ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    jdbc:
      dialect: postgresql

service:
  inventory:
    base-url: "http://localhost:9092/api/inventory"
  payment:
    base-url: "http://localhost:9093/api/payment"