server:
  port: 9092

spring:
  application:
    name: "Mini-E-Commerce-Inventory-MS"
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    jdbc:
      dialect: postgresql